# deployment-example.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-server
  template:
    metadata:
      labels:
        app: my-web-server
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.6