# .github/workflows/ci.yml

# 1. Give your workflow a name
name: Learning GitHub Actions

# 2. Define the event that triggers the workflow
on:
  push:
    branches:
      - feature/ci-pipeline

# 3. Define the jobs that the workflow will run
jobs:
  # Define a single job named "hello-world-job"
  hello-world-job:
    # 4. Specify the runner (virtual machine) to use
    runs-on: ubuntu-latest

    # 5. Define the steps to be executed
    steps:
      # A single step to print a message
      - name: Say Hello
        run: echo "Hello, World! I'm running my first GitHub Actions workflow!"