# .github/workflows/ci.yml

name: Build and Deploy Application

on:
  push:
    branches:
      - feature/ci-pipeline
  pull_request:
    branches:
      - main

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the User Service image
        run: |
          docker build -t user-service-image ./user-service